config/routes.rb
Rails.application.routes.draw do

  get 'welcome', to: 'pages#welcome'
  get 'friends', to: 'pages#friends'
  get 'users/sign_in', to: 'pages#welcome'
  get 'users/sign_up', to: 'pages#welcome'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'bills#index'

  post 'bills/update_state', to: 'bills#update_state'
  get 'my_bills', to: 'bills#my_bills'
  get 'my_charges', to: 'bills#my_charges'
  get 'settings', to: 'settings#edit'
  post 'update_settings', to: 'settings#update'
  resources :bills
  post 'cancel', to: 'bills#cancel'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :payee, class_name: "User", foreign_key: "payee_id"
  belongs_to :payer, class_name: "User", foreign_key: "payer_id"

  # scope :recent, -> { where("state == 'New' OR state == 'Accepted' OR state == 'Dispute' OR updated_at > " + (Time.now - 7.days)).order("updated_at DESC") }
  scope :recent, -> { where(["state = ? or state = ? or state = ? or updated_at > ?", 'New', 'Accepted', 'Dispute', (Time.now - 7.days)]).order("updated_at DESC") }
  # scope :recent_and_payed?, -> { where("state == 'New' OR state == 'Accepted' OR state == 'Dispute' OR state == 'Paid?' OR updated_at > " + (Time.now - 7.days)).order("updated_at DESC") }
  scope :recent_and_paid?, -> { where(["state = ? or state = ? or state = ? or state = ? or updated_at > ?", 'New', 'Accepted', 'Dispute', 'Paid?', (Time.now - 7.days)]).order("updated_at DESC") }
  scope :in_progress, -> { where(["state = ? or state = ? or state = ? or state = ?", 'New', 'Accepted', 'Dispute', 'Paid?']).order("updated_at DESC") }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :charges, class_name: "Bill", foreign_key: "payee_id"
  has_many :bills, class_name: "Bill", foreign_key: "payer_id"

  has_many :debtors, -> { where(["state = ? or state = ? or state = ? or state = ?", 'New', 'Accepted', 'Dispute', 'Paid?']).uniq }, through: :charges, source: :payer
  has_many :creditors, -> { where(["state = ? or state = ? or state = ? or state = ?", 'New', 'Accepted', 'Dispute', 'Paid?']).uniq }, through: :bills, source: :payee
  has_many :recent_debtors, -> { where(["state = ? or state = ? or state = ? or state = ? or bills.updated_at > ?", 'New', 'Accepted', 'Dispute', 'Paid?', (Time.now - 7.days)]).uniq }, through: :charges, source: :payer
  has_many :recent_creditors, -> { where(["state = ? or state = ? or state = ? or bills.updated_at > ?", 'New', 'Accepted', 'Dispute', (Time.now - 7.days)]).uniq }, through: :bills, source: :payee

  def avator_path(size)
    "https://graph.facebook.com/" + fbid.to_s + "/picture?width=" + size.to_s + "&height=" + size.to_s
  end

  def self.from_facebook(auth)
    user = where({:fbid => auth.uid}).first_or_create! do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
    user.name = auth.info.name
    user.email = auth.info.email
    user.fbtoken = auth.credentials.token
    user.save
    return user
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :login_required
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = current_user.bills.all
    @charges = current_user.charges.all
    @debtors = current_user.debtors.all  # 欠我錢的
    @creditors = current_user.creditors.all  # 我欠錢的
    @recent_debtors = current_user.recent_debtors.all  # 欠我錢的
    @recent_creditors = current_user.recent_creditors.all  # 我欠錢的
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = current_user.charges.new
    @graph = Koala::Facebook::API.new(current_user.fbtoken)
    @friends = @graph.get_connections("me", "friends")
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    fail = false
    @bills = []
    @payers = []
    @bills_total = params['total']
    pc = 0

    if params['cancel'] == 'true'
      params['bills'].each do |b_id|
        current_user.charges.find(b_id).delete
      end
    else

      params['payers'].each do |payer_fbid|
        pc += 1
        @payer = User.where({:fbid => payer_fbid}).first_or_create! do |user|
          user.email = Devise.friendly_token[0,20] + '@facebook.com'
          user.password = Devise.friendly_token[0,20]
        end
        @payers << @payer
        for i in 1..params['bill'].length
          @bill = current_user.charges.build(params.require('bill').require((i-1).to_s).permit(:name, :description, :unit_price, :quantity, :total_price))
          @bill.payer = @payer
          @bill.state = "New"
          @bill.splits_to = params['total']['splits_to']
          if !@bill.save
            fail = true
          end
          @bills << @bill
        end

        # params.require('bill').require('0').permit(:name, :description, :unit_price, :quantity, :total_price)
        @crb = current_user.charges.new
      end
    end

    if fail
      flash[:alert] = '儲存失敗。'
      redirect_to new_bill_path
    elsif params['cancel'] == 'true'
      flash[:success] = '已撤銷。'
      redirect_to bills_path
    else
      flash[:success] = '已簽發。'
      render :create_success
    end


    # respond_to do |format|
    #   if @bill.save
    #     format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
    #     format.json { render :show, status: :created, location: @bill }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @bill.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def update_state
    if params.has_key?("multiple")
      bill_ids = params['bill_ids'].split(',')
    else
      bill_ids = [params['bill_id']]
    end

    has_failed = false
    bill_ids.each do |bill_id|
      bill = Bill.find(bill_id)
      case params['state']
      when 'Canceled'
        if bill.payee == current_user && bill.state != 'Canceled' && bill.state != 'Paid?' && bill.state != 'Paid'
          bill.state = 'Canceled'
          bill.save
          flash[:success] = '撤銷成功。'
        else
          has_failed = true
        end
      when 'Paid'
        if bill.payee == current_user && bill.state != 'Canceled'
          bill.state = 'Paid'
          bill.save
          flash[:success] = '已確認付款。'
        else
          has_failed = true
        end
      when 'Accepted'
        if bill.payer == current_user && bill.state != 'Canceled' && bill.state != 'Paid' && bill.state != 'Paid?'
          bill.state = 'Accepted'
          bill.save
          flash[:success] = '已承諾付款。'
        else
          has_failed = true
        end
      when 'Paid?'
        if bill.payer == current_user && bill.state != 'Canceled'
          bill.state = 'Paid?'
          bill.save
          flash[:success] = '已回報付款。'
        else
          has_failed = true
        end
      when 'Dispute'
        if bill.payer == current_user && bill.state != 'Dispute' && bill.state != 'Accepted' && bill.state != 'Canceled' && bill.state != 'Paid?' && bill.state != 'Paid'
          bill.state = 'Dispute'
          bill.save
          flash[:success] = '已標示為異議。'
        else
          has_failed = true
        end
      end
    end

    if has_failed
      flash[:alert] = '並非所有操作都能被執行。'
    end

    redirect_to root_path
  end

  def my_bills
    @my_bills = current_user.bills
    render 'my_bills'
  end

  def my_charges
    @my_charges = current_user.charges
    render 'my_charges'
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:name, :description, :unit_price, :quantity, :total_price)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.haml
= form_for @bill do |f|
  - if @bill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bill.errors.count, "error")} prohibited this bill from being saved:"
      %ul
        - @bill.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :unit_price
    = f.text_field :unit_price
  .field
    = f.label :quantity
    = f.number_field :quantity
  .field
    = f.label :total_price
    = f.text_field :total_price
  .field
    = f.label :payer
    = f.text_field :payer
  .actions
    = f.submit 'Save'

app/views/bills/create_success.html.haml
%h1 剛剛簽發的帳單

.paper
  .to
    - @payers.each do |payer|
      = payer.name
  .split
    - if @bills_total['payers'].to_i > 1
      - if @bills_total['splits_to'].to_i == 1
        個別支付
      - if @bills_total['payers'].to_i == @bills_total['splits_to'].to_i
        均分
      - if @bills_total['payers'].to_i < @bills_total['splits_to'].to_i
        均分，算我一份

  %table{cellspacing: "0", cellpadding: "0"}
    %col{width: "200"}
    %col{width: "100"}
    %col{width: "70"}
    %col{width: "80"}
    %thead
      %tr
        %th 項目
        %th 單價
        %th 數量
        %th 金額
    %tbody#bill_table.bill_table
      - subtotal = 0
      - i = 0
      - @bills.each do |bill|
      - if i < @bills_total['bills'].to_i
        - i += 1
          - subtotal += bill.unit_price.to_i*bill.quantity.to_i
          %tr#bill_row_0.bill_row
            %td
              .input.name= bill.name
              .textarea.description= bill.description
            %td
              / %span.show-for-medium-up NT$
              .input.unit_price= bill.unit_price
            %td
              .input.quantity= bill.quantity
            %td
              NT$
              %span.total_price= bill.unit_price.to_i*bill.quantity.to_i
              - #loso
      %tr#new_row.total_row
        %td
        %td
        %td
        %td
          .subtotal_c
            總計：NT$
            %span.subtotal= subtotal
            - if @bills_total['payers'].to_i > 1
              - if @bills_total['splits_to'].to_i == 1
                %span.split.show_no_splid
                  %br
                  合計收取：總額
                  ×
                  %span.splits= @bills_total['payers']
                  \= NT$
                  %span.split_total= subtotal*@bills_total['payers'].to_i
              - else
                -
                %span.split.show_splid
                  %br
                  每人支付：總額
                  \/
                  %span.splits= @bills_total['splits_to']
                  \= NT$
                  %span.split_total= subtotal/@bills_total['splits_to'].to_f
                  (均分)
  .eol 　
  .from
    = current_user.name



  %input#bills_c{name: "total[bills]", type: "hidden", value: 1}
  %input#payers_c{name: "total[payers]", type: "hidden", value: 0}
  %input#splits_to{name: "total[splits_to]", type: "hidden", value: 0}
  / = f.text_field :payer
.actions

.actions
  = form_for @crb do |f|
    %input#c{name: "cancel", type: "hidden", value: "true"}
    %select#bills{name: "bills[]", multiple: "multiple", style: "display: none;"}
      - @bills.each do |bill|
        %option{value: "#{bill['id']}", selected: "selected"}= bill['id']
    = f.submit '撤銷', class: "button alert", :data => { :confirm => 'Are you sure?' }
    　
    = link_to '返回', bills_path, class: "button"
  　

  　

app/views/bills/edit.html.haml
%h1 Editing bill

= render 'form'

= link_to 'Show', @bill
\|
= link_to 'Back', bills_path

app/views/bills/index.html.haml
%h2 我未付款的帳單
%table{cellspacing: "0", cellpadding: "0"}
  %thead
    %tr
      %th
      %th.show-for-medium-up 日期
      %th 簽發人
      %th 項目名稱
      %th 總額
      %th 狀態
  %tbody
    - dc_c = 0
    - @creditors.each do |creditor|
      - dc_c += 1
      - bill_id_s = ''
      - all_names = ''
      - all_names_t = 0
      - n_c = 0
      - d_c = 0
      - a_c = 0
      - pp_c = 0
      - p_c = 0
      - latest_date = creditor.charges.in_progress.where(payer: current_user.id)[0].updated_at
      %tr.detail{class: "bill_mybill_#{dc_c}"}
        %td{colspan: "7"}
          .paper.list
            .list
              單筆明細
              %table{cellspacing: "0", cellpadding: "0"}
                %thead
                  %tr
                    %th.show-for-medium-up 日期
                    %th 項目
                    %th 單價
                    %th 數量
                    %th 金額
                    %th 狀態
                    %th 操作
                %tbody#bill_table.bill_table
                  - subtotal = 0
                  - creditor.charges.in_progress.where(payer: current_user.id).each do |bill|
                    - n_c += 1 if bill.state == 'New'
                    - d_c += 1 if bill.state == 'Dispute'
                    - a_c += 1 if bill.state == 'Accepted'
                    - pp_c += 1 if bill.state == 'Paid?'
                    - p_c += 1 if bill.state == 'Paid'
                    - if bill.state != 'Canceled'
                      - if bill.state != 'Paid?' && bill.state != 'Paid' && bill.state != 'Dispute'
                        - subtotal += bill.unit_price.to_i*bill.quantity.to_i
                      - bill_id_s += bill.id.to_s + ','
                      - latest_date = bill.updated_at if bill.updated_at > latest_date
                      - if all_names_t == 0
                        - all_names += bill.name
                        - all_names_t += 1
                      - elsif (all_names + '、' + bill.name).length < 20
                        - all_names += '、' + bill.name
                        - all_names_t += 1
                      %tr.bill_row
                        %td.show-for-medium-up= bill.updated_at.strftime('%Y 年 %-m 月 %e 日')
                        %td
                          .input.name= bill.name
                          .textarea.description= bill.description
                        %td
                          / %span.show-for-medium-up NT$
                          .input.unit_price= bill.unit_price
                        %td
                          .input.quantity= bill.quantity
                        %td
                          NT$
                          %span.total_price= bill.unit_price.to_i*bill.quantity.to_i
                          - #loso
                        %td= raw state_tag bill.state
                        %td
                          - if (bill.state != 'Accepted' && bill.state != 'Canceled' && bill.state != 'Paid?' && bill.state != 'Paid' ) # Can be Accepted
                            = form_tag bills_update_state_path do |f|
                              = hidden_field_tag :bill_id, bill.id
                              = hidden_field_tag :state, 'Accepted'
                              = submit_tag "承諾支付", data: { confirm: "確定承諾支付「#{bill.name}」？此動作無法復原。" }
                          - if (bill.state != 'Canceled' && bill.state != 'Paid' && bill.state != 'Paid?') # Can be Paid?
                            = form_tag bills_update_state_path do |f|
                              = hidden_field_tag :bill_id, bill.id
                              = hidden_field_tag :state, 'Paid?'
                              = submit_tag "回報已付款", data: { confirm: "確定將「#{bill.name}」標為已付款？此動作無法復原。" }
                          - if (bill.state != 'Dispute' && bill.state != 'Accepted' && bill.state != 'Canceled' && bill.state != 'Paid?' && bill.state != 'Paid' ) # Can be Dispute
                            = form_tag bills_update_state_path do |f|
                              = hidden_field_tag :bill_id, bill.id
                              = hidden_field_tag :state, 'Dispute'
                              = submit_tag "異議", data: { confirm: "確定將「#{bill.name}」標示為異議？" }
                          - if (bill.state == 'Paid?')
                            等待帳單簽發人確認中
            .list-actions.center
              操作：
              = #link_to '嗨', update_bill_path(1), {controller: "bills", method:  "update", bill: "23847293", state: "adk" }
              = #button_to 'My link',bills_update_state_path(multiple: "multiple", bill_ids: bill_id_s, state: 'Canceled')

              = form_tag bills_update_state_path do |f|
                = hidden_field_tag :multiple, 'multiple'
                = hidden_field_tag :bill_ids, bill_id_s
                = hidden_field_tag :state, 'Accepted'
                = submit_tag "承諾支付", data: { confirm: "確定全部承諾支付？此動作無法復原。" }
              = form_tag bills_update_state_path do |f|
                = hidden_field_tag :multiple, 'multiple'
                = hidden_field_tag :bill_ids, bill_id_s
                = hidden_field_tag :state, 'Paid?'
                = submit_tag "回報已付款", data: { confirm: "確定全部標為已付款？此動作無法復原。" }
              = form_tag bills_update_state_path do |f|
                = hidden_field_tag :multiple, 'multiple'
                = hidden_field_tag :bill_ids, bill_id_s
                = hidden_field_tag :state, 'Dispute'
                = submit_tag "異議", data: { confirm: "確定全部標示為異議？" }

      %tr.title{class: "bill_mybill_#{dc_c}", onclick: "$('.bill_mybill_#{dc_c}').toggleClass('open')"}
        %td
          .collapse= image_tag('orbital_arrow_right.png')
        %td.show-for-medium-up.earliest_date= latest_date.strftime('%Y 年 %-m 月 %e 日')
        %td= creditor.name
        %td.names
          - if creditor.charges.in_progress.where(payee: current_user.id).length > all_names_t
            = all_names + '，以及其他 ' + (debtor.bills.in_progress.where(payee: current_user.id).length - all_names_t).to_s + ' 個項目'
          - else
            = all_names
        %td.subtotal
          %span.show-for-medium-up NT$
          = subtotal
        %td.state
          = raw state_tag 'New: ' + n_c.to_s if n_c > 0
          = raw state_tag 'Dispute: ' + d_c.to_s if d_c > 0
          = raw state_tag 'Accepted: ' + a_c.to_s if a_c > 0
          = raw state_tag 'Paid?: ' + pp_c.to_s if pp_c > 0
          = raw state_tag 'Paid: ' + p_c.to_s if p_c > 0


%h2
  我簽發的未結束帳單
  %small= link_to '簽發新帳單', new_bill_path
%table{cellspacing: "0", cellpadding: "0"}
  %thead
    %tr
      %th
      %th.show-for-medium-up 日期
      %th 付款人
      %th 項目名稱
      %th 總額
      %th 狀態
  %tbody
    - dc_c = 0
    - @debtors.each do |debtor|
      - dc_c += 1
      - bill_id_s = ''
      - all_names = ''
      - all_names_t = 0
      - n_c = 0
      - d_c = 0
      - a_c = 0
      - pp_c = 0
      - p_c = 0
      - latest_date = debtor.bills.in_progress.where(payee: current_user.id)[0].updated_at
      %tr.detail{class: "bill_mybill_#{dc_c}"}
        %td{colspan: "7"}
          .paper.list
            .list
              單筆明細
              %table{cellspacing: "0", cellpadding: "0"}
                %thead
                  %tr
                    %th 日期
                    %th 項目
                    %th 單價
                    %th 數量
                    %th 金額
                    %th 狀態
                    %th 操作
                %tbody#bill_table.bill_table
                  - subtotal = 0
                  - debtor.bills.in_progress.where(payee: current_user.id).each do |bill|
                    - n_c += 1 if bill.state == 'New'
                    - d_c += 1 if bill.state == 'Dispute'
                    - a_c += 1 if bill.state == 'Accepted'
                    - pp_c += 1 if bill.state == 'Paid?'
                    - p_c += 1 if bill.state == 'Paid'
                    - if bill.state != 'Canceled'
                      - if bill.state != 'Paid?' && bill.state != 'Paid'
                        - subtotal += bill.unit_price.to_i*bill.quantity.to_i
                      - bill_id_s += bill.id.to_s + ','
                      - latest_date = bill.updated_at if bill.updated_at > latest_date
                      - if all_names_t == 0
                        - all_names += bill.name
                        - all_names_t += 1
                      - elsif (all_names + '、' + bill.name).length < 20
                        - all_names += '、' + bill.name
                        - all_names_t += 1
                      %tr.bill_row
                        %td= bill.updated_at.strftime('%Y 年 %-m 月 %e 日')
                        %td
                          .input.name= bill.name
                          .textarea.description= bill.description
                        %td
                          / %span.show-for-medium-up NT$
                          .input.unit_price= bill.unit_price
                        %td
                          .input.quantity= bill.quantity
                        %td
                          NT$
                          %span.total_price= bill.unit_price.to_i*bill.quantity.to_i
                          - #loso
                        %td= raw state_tag bill.state
                        %td
                          - if (bill.state != 'Canceled' && bill.state != 'Paid?' && bill.state != 'Paid' ) # Can be Canceled
                            = form_tag bills_update_state_path do |f|
                              = hidden_field_tag :bill_id, bill.id
                              = hidden_field_tag :state, 'Canceled'
                              = submit_tag "撤銷", data: { confirm: "確定撤銷「#{bill.name}」？此動作無法復原。" }
                          - if (bill.state != 'Canceled' && bill.state != 'Paid') # Can be Paid
                            = form_tag bills_update_state_path do |f|
                              = hidden_field_tag :bill_id, bill.id
                              = hidden_field_tag :state, 'Paid'
                              = submit_tag "標為已付款", data: { confirm: "確定將「#{bill.name}」標為已付款？此動作無法復原。" }
            .list-actions.center
              操作：
              = #link_to '嗨', update_bill_path(1), {controller: "bills", method:  "update", bill: "23847293", state: "adk" }
              = #button_to 'My link',bills_update_state_path(multiple: "multiple", bill_ids: bill_id_s, state: 'Canceled')
              = form_tag bills_update_state_path do |f|
                = hidden_field_tag :multiple, 'multiple'
                = hidden_field_tag :bill_ids, bill_id_s
                = hidden_field_tag :state, 'Canceled'
                = submit_tag "撤銷", data: { confirm: "確定全部撤銷？此動作無法復原。" }
              = form_tag bills_update_state_path do |f|
                = hidden_field_tag :multiple, 'multiple'
                = hidden_field_tag :bill_ids, bill_id_s
                = hidden_field_tag :state, 'Paid'
                = submit_tag "標為已付款", data: { confirm: "確定全部標為已付款？此動作無法復原。" }
      %tr.title{class: "bill_mybill_#{dc_c}", onclick: "$('.bill_mybill_#{dc_c}').toggleClass('open')"}
        %td
          .collapse= image_tag('orbital_arrow_right.png')
        %td.show-for-medium-up.earliest_date= latest_date.strftime('%Y 年 %-m 月 %e 日')
        %td= debtor.name
        %td.names
          - if debtor.bills.in_progress.where(payee: current_user.id).length > all_names_t
            = all_names + '，以及其他 ' + (debtor.bills.in_progress.where(payee: current_user.id).length - all_names_t).to_s + ' 個項目'
          - else
            = all_names
        %td.subtotal
          %span.show-for-medium-up NT$
          = subtotal
        %td.state
          = raw state_tag 'New: ' + n_c.to_s if n_c > 0
          = raw state_tag 'Dispute: ' + d_c.to_s if d_c > 0
          = raw state_tag 'Accepted: ' + a_c.to_s if a_c > 0
          = raw state_tag 'Paid?: ' + pp_c.to_s if pp_c > 0
          = raw state_tag 'Paid: ' + p_c.to_s if p_c > 0


:javascript
  $.fn.moveUp = function() {
    $.each(this, function() {
      $(this).after($(this).prev());
    });
  };
  $("tr.title").moveUp();
  $(".list-actions").moveUp();

app/views/bills/my_bills.html.haml
%table{cellspacing: "0", cellpadding: "0"}
  %thead
    %tr
      %th 日期
      %th 項目
      %th 簽發人
      %th 單價
      %th 數量
      %th 金額
      %th 狀態
  %tbody#bill_table.bill_table
    - @my_bills.each do |bill|
      %tr.bill_row
        %td= bill.updated_at.strftime('%Y 年 %-m 月 %e 日')
        %td
          .input.name= bill.name
          .textarea.description= bill.description
        %td
          .input.unit_price= bill.payee.name
        %td
          / %span.show-for-medium-up NT$
          .input.unit_price= bill.unit_price
        %td
          .input.quantity= bill.quantity
        %td
          NT$
          %span.total_price= bill.unit_price.to_i*bill.quantity.to_i
        %td= raw state_tag bill.state

app/views/bills/my_charges.html.haml
%table{cellspacing: "0", cellpadding: "0"}
  %thead
    %tr
      %th 日期
      %th 項目
      %th 付款人
      %th 單價
      %th 數量
      %th 金額
      %th 狀態
  %tbody#bill_table.bill_table
    - @my_charges.each do |bill|
      %tr.bill_row
        %td= bill.updated_at.strftime('%Y 年 %-m 月 %e 日')
        %td
          .input.name= bill.name
          .textarea.description= bill.description
        %td
          .input.unit_price= bill.payer.name
        %td
          / %span.show-for-medium-up NT$
          .input.unit_price= bill.unit_price
        %td
          .input.quantity= bill.quantity
        %td
          NT$
          %span.total_price= bill.unit_price.to_i*bill.quantity.to_i
        %td= raw state_tag bill.state

app/views/bills/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @bill.name
%p
  %b Description:
  = @bill.description
%p
  %b Unit price:
  = @bill.unit_price
%p
  %b Quantity:
  = @bill.quantity
%p
  %b Total price:
  = @bill.total_price

= link_to 'Edit', edit_bill_path(@bill)
\|
= link_to 'Back', bills_path