config/routes.rb
Rails.application.routes.draw do

  get 'welcome', to: 'pages#welcome'
  get 'friends', to: 'pages#friends'
  get 'users/sign_in', to: 'pages#welcome'
  get 'users/sign_up', to: 'pages#welcome'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'bills#index'

  post 'bills/update_state', to: 'bills#update_state'
  get 'my_bills', to: 'bills#my_bills'
  get 'my_charges', to: 'bills#my_charges'
  get 'settings', to: 'settings#edit'
  post 'update_settings', to: 'settings#update'
  resources :bills
  post 'cancel', to: 'bills#cancel'

end

app/helpers/layouts_helper.rb
module LayoutsHelper

  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end

  def get_avator_url(id, size)
    "https://graph.facebook.com/" + id.to_s + "/picture?width=" + size.to_s + "&height=" + size.to_s
  end

  def state_tag(state)
    state_class = state
    state_class = 'New' if state =~ /^New/
    state_class = 'Dispute' if state =~ /^Dispute/
    state_class = 'Accepted' if state =~ /^Accepted/
    state_class = 'Paid' if state =~ /^Paid/
    state_class = 'Paid q' if state =~ /^Paid\?/
    '<span class="label ' + state_class + '"> ' + state + ' </span>'
  end

end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div data-alert class="alert-box">
    <%= notice %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>
<% if alert %>
  <div data-alert class="alert-box alert">
    <%= alert %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>
<% if flash[:warning] %>
  <div data-alert class="alert-box warning">
    <%= flash[:warning] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>
<% if flash[:success] %>
  <div data-alert class="alert-box success">
    <%= flash[:success] %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/layouts/_menu.html.haml
%li
  %label 我的帳單
%li= link_to '儀表板', root_path
%li= link_to '簽發新帳單', new_bill_path
%li= link_to '我簽發的帳單列表', my_charges_path
%li= link_to '簽發給我的帳單列表', my_bills_path
%li
  %label 帳戶
%li= link_to '好友列表', friends_path
%li= link_to '個人設定', settings_path
%li= link_to '登出', destroy_user_session_path, method: :delete

app/views/layouts/application.html.erb
<div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap">
    <div class="container">
      <nav class="nav tab-bar">
        <section class="left-small">
          <a class="left-off-canvas-toggle menu-icon"><span></span></a>
        </section>

        <section class="middle tab-bar-section content">
          <h1 class="title"><%= link_to @app_name, root_path %></h1>
          <div class="top-bar" data-topbar data-options="is_hover: false">
            <section class="top-bar-section">
              <ul>
                <li class="has-dropdown">
                  <a>
                    <img src="<%= current_user.avator_path(100) %>">
                    嗨，<%= current_user.name %>
                  </a>
                  <ul class="dropdown">
                    <%= render 'layouts/menu' %>
                  </ul>
                </li>
              </ul>
            </section>
          </div>
        </section>
      </nav>
      <div class="content main-content">
        <aside class="menu left-menu left-off-canvas-menu">
          <ul class="list off-canvas-list">
            <li class="overview">
              <div class="out">總共積欠：<div class="money">NT$<%= current_user.bills.in_progress.sum(:total_price) %></div></div>
              <div class="in">總共未收：<div class="money">NT$<%= current_user.charges.in_progress.sum(:total_price) %></div></div>
            </li>
            <%= render 'layouts/menu' %>
          </ul>
        </aside>
        <section class="main-section">
          <%= render 'layouts/alerts' %>

          <%= yield %>

        </section>
      </div>
      <a class="exit-off-canvas"></a>
    </div>
  </div>
</div>

<% parent_layout "base" %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.5, user-scalable=no" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <%= render_page_title_tag %>
  <%= render_page_description_meta_tag %>
  <%= render_page_keywords_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :modernizr %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!--[if lt IE 8]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
  <![endif]-->

  <%= yield %>
  <script>window.onload = $(function(){ $(document).foundation(); });</script>
  <%= javascript_include_tag :view %>
  <script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
    function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
    e=o.createElement(i);r=o.getElementsByTagName(i)[0];
    e.src='//www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','<%= @google_analytics_id %>','auto');ga('send','pageview');
  </script>
</body>
</html>